#! /usr/bin/env bash

if [ -z "$NODE_ENV" ]; then
  npm run watch
  exit 0
fi

if [ "$NODE_ENV" == "development" ]; then
  npm run watch
  exit 0
fi

if [ "$NODE_ENV" == "test" ]; then
  case "$SCOPE" in
  "unit")
      npm run test-unit
      ;;
  "integ")
      npm run test-integ
      ;;
  *)
      npm run test
      ;;
  esac
  exit 0
fi

npm start
exit 0
